import { Inter } from "next/font/google";
import "./globals.css";
import StoreProvider from "./storeProvider";
import { Toaster } from "sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className} text-black dark:text-white`}>
        <Toaster position="top-right" richColors />
        <StoreProvider>{children}</StoreProvider>
      </body>
    </html>
  );
}
